name: Flask CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Flask app
        run: |
          start /B C:\Users\HP\AppData\Local\Programs\Python\Python312\python.exe app.py
