name: Flask CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code to D drive
        run: |
          if exist C:\FlaskProject rmdir /S /Q C:\FlaskProject
          git clone %GITHUB_SERVER_URL%/%GITHUB_REPOSITORY%.git C:\FlaskProject

      - name: Run Flask app from D drive
        run: |
          cd /d C:\FlaskProject
          start /B C:\Users\HP\AppData\Local\Programs\Python\Python312\python.exe app.py
