name: Flask CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Remove old folder from D drive
        run: |
          if exist D:\FlaskProject rmdir /S /Q D:\FlaskProject
        shell: cmd

      - name: Clone repo to D drive
        run: |
          git clone %GITHUB_SERVER_URL%/%GITHUB_REPOSITORY%.git D:\FlaskProject
        shell: cmd

      - name: Run Flask app from D drive
        run: |
          cd /d D:\FlaskProject
          start /B C:\Users\HP\AppData\Local\Programs\Python\Python312\python.exe app.py
        shell: cmd
