name: Flask CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: D:/FlaskProject

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd D:/FlaskProject
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          cd D:/FlaskProject
          start /B python app.py
